/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_int_type = 1,
  sym_float_type = 2,
  sym_let_kw = 3,
  sym_str_type = 4,
  sym_comment = 5,
  anon_sym_EQ = 6,
  anon_sym_SEMI = 7,
  anon_sym_if = 8,
  anon_sym_else = 9,
  anon_sym_while = 10,
  anon_sym_for = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_print = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_EQ_EQ = 17,
  anon_sym_LT = 18,
  anon_sym_PLUS = 19,
  sym_identifier = 20,
  sym_number = 21,
  anon_sym_DQUOTE = 22,
  aux_sym_string_token1 = 23,
  sym_source_file = 24,
  sym__statement = 25,
  sym_variable_declaration = 26,
  sym_assignment = 27,
  sym_if_statement = 28,
  sym_while_statement = 29,
  sym_for_statement = 30,
  sym_print_statement = 31,
  sym_block = 32,
  sym__datatype = 33,
  sym__expression = 34,
  sym_binary_expression = 35,
  sym_string = 36,
  aux_sym_source_file_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_int_type] = "int_type",
  [sym_float_type] = "float_type",
  [sym_let_kw] = "let_kw",
  [sym_str_type] = "str_type",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_print] = "print",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT] = "<",
  [anon_sym_PLUS] = "+",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_assignment] = "assignment",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_for_statement] = "for_statement",
  [sym_print_statement] = "print_statement",
  [sym_block] = "block",
  [sym__datatype] = "_datatype",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_int_type] = sym_int_type,
  [sym_float_type] = sym_float_type,
  [sym_let_kw] = sym_let_kw,
  [sym_str_type] = sym_str_type,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_assignment] = sym_assignment,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_for_statement] = sym_for_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_block] = sym_block,
  [sym__datatype] = sym__datatype,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_int_type] = {
    .visible = true,
    .named = true,
  },
  [sym_float_type] = {
    .visible = true,
    .named = true,
  },
  [sym_let_kw] = {
    .visible = true,
    .named = true,
  },
  [sym_str_type] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__datatype] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_body = 2,
  field_condition = 3,
  field_consequence = 4,
  field_left = 5,
  field_name = 6,
  field_operator = 7,
  field_right = 8,
  field_value = 9,
  field_vartype = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
  [field_vartype] = "vartype",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 2},
  [5] = {.index = 9, .length = 3},
  [6] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
    {field_consequence, 2},
  [2] =
    {field_body, 2},
    {field_condition, 1},
  [4] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [7] =
    {field_name, 0},
    {field_value, 2},
  [9] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [12] =
    {field_name, 1},
    {field_value, 3},
    {field_vartype, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 4,
  [8] = 4,
  [9] = 2,
  [10] = 2,
  [11] = 2,
  [12] = 4,
  [13] = 13,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 18,
  [22] = 20,
  [23] = 23,
  [24] = 24,
  [25] = 16,
  [26] = 26,
  [27] = 27,
  [28] = 18,
  [29] = 13,
  [30] = 16,
  [31] = 23,
  [32] = 24,
  [33] = 26,
  [34] = 27,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 35,
  [43] = 37,
  [44] = 39,
  [45] = 38,
  [46] = 46,
  [47] = 46,
  [48] = 46,
  [49] = 41,
  [50] = 36,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 53,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 60,
  [61] = 57,
  [62] = 58,
  [63] = 63,
  [64] = 63,
  [65] = 60,
  [66] = 23,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 69,
  [71] = 68,
  [72] = 67,
  [73] = 73,
  [74] = 73,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 79,
  [82] = 73,
  [83] = 78,
  [84] = 76,
  [85] = 85,
  [86] = 79,
  [87] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 66,
        '(', 34,
        ')', 35,
        '+', 41,
        '/', 3,
        ';', 29,
        '<', 40,
        '=', 28,
        'e', 50,
        'f', 51,
        'i', 46,
        'l', 45,
        'p', 55,
        's', 63,
        'w', 47,
        '{', 37,
        '}', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '=') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 's') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        ')', 35,
        '+', 41,
        '/', 3,
        ';', 29,
        '<', 40,
        '=', 4,
        'f', 51,
        'i', 46,
        'l', 45,
        'p', 55,
        's', 63,
        'w', 47,
        '{', 37,
        '}', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_int_type);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_int_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_float_type);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_float_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_let_kw);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_let_kw);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_str_type);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_str_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_print);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == 'o') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(69);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 15},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 15},
  [56] = {.lex_state = 15},
  [57] = {.lex_state = 15},
  [58] = {.lex_state = 15},
  [59] = {.lex_state = 15},
  [60] = {.lex_state = 15},
  [61] = {.lex_state = 15},
  [62] = {.lex_state = 15},
  [63] = {.lex_state = 15},
  [64] = {.lex_state = 15},
  [65] = {.lex_state = 15},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 67},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_int_type] = ACTIONS(1),
    [sym_float_type] = ACTIONS(1),
    [sym_let_kw] = ACTIONS(1),
    [sym_str_type] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(85),
    [sym__statement] = STATE(3),
    [sym_variable_declaration] = STATE(3),
    [sym_assignment] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_while_statement] = STATE(3),
    [sym_for_statement] = STATE(3),
    [sym_print_statement] = STATE(3),
    [sym_block] = STATE(3),
    [sym__datatype] = STATE(74),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_int_type] = ACTIONS(7),
    [sym_float_type] = ACTIONS(7),
    [sym_let_kw] = ACTIONS(7),
    [sym_str_type] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(4),
    [sym_variable_declaration] = STATE(4),
    [sym_assignment] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_while_statement] = STATE(4),
    [sym_for_statement] = STATE(4),
    [sym_print_statement] = STATE(4),
    [sym_block] = STATE(4),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(5),
    [sym_variable_declaration] = STATE(5),
    [sym_assignment] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_while_statement] = STATE(5),
    [sym_for_statement] = STATE(5),
    [sym_print_statement] = STATE(5),
    [sym_block] = STATE(5),
    [sym__datatype] = STATE(74),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_int_type] = ACTIONS(7),
    [sym_float_type] = ACTIONS(7),
    [sym_let_kw] = ACTIONS(7),
    [sym_str_type] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_for] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_assignment] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_while_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_print_statement] = STATE(6),
    [sym_block] = STATE(6),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(39),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(5),
    [sym_variable_declaration] = STATE(5),
    [sym_assignment] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_while_statement] = STATE(5),
    [sym_for_statement] = STATE(5),
    [sym_print_statement] = STATE(5),
    [sym_block] = STATE(5),
    [sym__datatype] = STATE(74),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_int_type] = ACTIONS(43),
    [sym_float_type] = ACTIONS(43),
    [sym_let_kw] = ACTIONS(43),
    [sym_str_type] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(46),
    [anon_sym_while] = ACTIONS(49),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_print] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(58),
    [sym_identifier] = ACTIONS(61),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_assignment] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_while_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_print_statement] = STATE(6),
    [sym_block] = STATE(6),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_int_type] = ACTIONS(64),
    [sym_float_type] = ACTIONS(64),
    [sym_let_kw] = ACTIONS(64),
    [sym_str_type] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(67),
    [anon_sym_while] = ACTIONS(70),
    [anon_sym_for] = ACTIONS(73),
    [anon_sym_print] = ACTIONS(76),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(41),
    [sym_identifier] = ACTIONS(82),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_assignment] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_while_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_print_statement] = STATE(6),
    [sym_block] = STATE(6),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(85),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_assignment] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_while_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_print_statement] = STATE(6),
    [sym_block] = STATE(6),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(87),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(7),
    [sym_variable_declaration] = STATE(7),
    [sym_assignment] = STATE(7),
    [sym_if_statement] = STATE(7),
    [sym_while_statement] = STATE(7),
    [sym_for_statement] = STATE(7),
    [sym_print_statement] = STATE(7),
    [sym_block] = STATE(7),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(89),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(10)] = {
    [sym__statement] = STATE(12),
    [sym_variable_declaration] = STATE(12),
    [sym_assignment] = STATE(12),
    [sym_if_statement] = STATE(12),
    [sym_while_statement] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_print_statement] = STATE(12),
    [sym_block] = STATE(12),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(91),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(11)] = {
    [sym__statement] = STATE(8),
    [sym_variable_declaration] = STATE(8),
    [sym_assignment] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_while_statement] = STATE(8),
    [sym_for_statement] = STATE(8),
    [sym_print_statement] = STATE(8),
    [sym_block] = STATE(8),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(93),
    [sym_identifier] = ACTIONS(35),
  },
  [STATE(12)] = {
    [sym__statement] = STATE(6),
    [sym_variable_declaration] = STATE(6),
    [sym_assignment] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_while_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_print_statement] = STATE(6),
    [sym_block] = STATE(6),
    [sym__datatype] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_int_type] = ACTIONS(21),
    [sym_float_type] = ACTIONS(21),
    [sym_let_kw] = ACTIONS(21),
    [sym_str_type] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_for] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(95),
    [sym_identifier] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    ACTIONS(99), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [20] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_else,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(103), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [42] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_else,
    ACTIONS(101), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(103), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [64] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(111), 10,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(111), 10,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [104] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(115), 10,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [124] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(115), 10,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [144] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(117), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [163] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(115), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(117), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [201] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(123), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(127), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [239] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(111), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(129), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [277] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(133), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [296] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(115), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(99), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [334] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(111), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [353] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(123), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(127), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [391] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(129), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [410] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(133), 9,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
      anon_sym_if,
      anon_sym_while,
      anon_sym_for,
      anon_sym_print,
      sym_identifier,
  [429] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 2,
      sym_identifier,
      sym_number,
    STATE(54), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym_variable_declaration,
    STATE(73), 1,
      sym__datatype,
    ACTIONS(141), 4,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
  [461] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 2,
      sym_identifier,
      sym_number,
    STATE(53), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [477] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 2,
      sym_identifier,
      sym_number,
    STATE(62), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [493] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(147), 2,
      sym_identifier,
      sym_number,
    STATE(60), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [509] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(149), 2,
      sym_identifier,
      sym_number,
    STATE(51), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(151), 2,
      sym_identifier,
      sym_number,
    STATE(64), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [541] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 2,
      sym_identifier,
      sym_number,
    STATE(55), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [557] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 2,
      sym_identifier,
      sym_number,
    STATE(56), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [573] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 2,
      sym_identifier,
      sym_number,
    STATE(65), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [589] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 2,
      sym_identifier,
      sym_number,
    STATE(58), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [605] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 2,
      sym_identifier,
      sym_number,
    STATE(59), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [621] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 2,
      sym_identifier,
      sym_number,
    STATE(57), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [637] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 2,
      sym_identifier,
      sym_number,
    STATE(61), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [653] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 2,
      sym_identifier,
      sym_number,
    STATE(63), 3,
      sym__expression,
      sym_binary_expression,
      sym_string,
  [669] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(41), 1,
      sym_variable_declaration,
    STATE(73), 1,
      sym__datatype,
    ACTIONS(141), 4,
      sym_int_type,
      sym_float_type,
      sym_let_kw,
      sym_str_type,
  [685] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 5,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [707] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [722] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_block,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [737] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_block,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [752] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_block,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [779] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [815] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_SEMI,
    ACTIONS(173), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_PLUS,
  [875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      sym_identifier,
      sym_number,
      anon_sym_DQUOTE,
  [884] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_block,
  [894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block,
  [904] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(84), 1,
      sym_assignment,
  [914] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(76), 1,
      sym_assignment,
  [924] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_block,
  [934] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym_identifier,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_identifier,
  [958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_EQ,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_EQ,
  [993] = 2,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(215), 1,
      aux_sym_string_token1,
  [1000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_EQ,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
  [1014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_EQ,
  [1021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
  [1028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
  [1035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_EQ,
  [1042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 20,
  [SMALL_STATE(15)] = 42,
  [SMALL_STATE(16)] = 64,
  [SMALL_STATE(17)] = 84,
  [SMALL_STATE(18)] = 104,
  [SMALL_STATE(19)] = 124,
  [SMALL_STATE(20)] = 144,
  [SMALL_STATE(21)] = 163,
  [SMALL_STATE(22)] = 182,
  [SMALL_STATE(23)] = 201,
  [SMALL_STATE(24)] = 220,
  [SMALL_STATE(25)] = 239,
  [SMALL_STATE(26)] = 258,
  [SMALL_STATE(27)] = 277,
  [SMALL_STATE(28)] = 296,
  [SMALL_STATE(29)] = 315,
  [SMALL_STATE(30)] = 334,
  [SMALL_STATE(31)] = 353,
  [SMALL_STATE(32)] = 372,
  [SMALL_STATE(33)] = 391,
  [SMALL_STATE(34)] = 410,
  [SMALL_STATE(35)] = 429,
  [SMALL_STATE(36)] = 445,
  [SMALL_STATE(37)] = 461,
  [SMALL_STATE(38)] = 477,
  [SMALL_STATE(39)] = 493,
  [SMALL_STATE(40)] = 509,
  [SMALL_STATE(41)] = 525,
  [SMALL_STATE(42)] = 541,
  [SMALL_STATE(43)] = 557,
  [SMALL_STATE(44)] = 573,
  [SMALL_STATE(45)] = 589,
  [SMALL_STATE(46)] = 605,
  [SMALL_STATE(47)] = 621,
  [SMALL_STATE(48)] = 637,
  [SMALL_STATE(49)] = 653,
  [SMALL_STATE(50)] = 669,
  [SMALL_STATE(51)] = 685,
  [SMALL_STATE(52)] = 696,
  [SMALL_STATE(53)] = 707,
  [SMALL_STATE(54)] = 722,
  [SMALL_STATE(55)] = 737,
  [SMALL_STATE(56)] = 752,
  [SMALL_STATE(57)] = 767,
  [SMALL_STATE(58)] = 779,
  [SMALL_STATE(59)] = 791,
  [SMALL_STATE(60)] = 803,
  [SMALL_STATE(61)] = 815,
  [SMALL_STATE(62)] = 827,
  [SMALL_STATE(63)] = 839,
  [SMALL_STATE(64)] = 851,
  [SMALL_STATE(65)] = 863,
  [SMALL_STATE(66)] = 875,
  [SMALL_STATE(67)] = 884,
  [SMALL_STATE(68)] = 894,
  [SMALL_STATE(69)] = 904,
  [SMALL_STATE(70)] = 914,
  [SMALL_STATE(71)] = 924,
  [SMALL_STATE(72)] = 934,
  [SMALL_STATE(73)] = 944,
  [SMALL_STATE(74)] = 951,
  [SMALL_STATE(75)] = 958,
  [SMALL_STATE(76)] = 965,
  [SMALL_STATE(77)] = 972,
  [SMALL_STATE(78)] = 979,
  [SMALL_STATE(79)] = 986,
  [SMALL_STATE(80)] = 993,
  [SMALL_STATE(81)] = 1000,
  [SMALL_STATE(82)] = 1007,
  [SMALL_STATE(83)] = 1014,
  [SMALL_STATE(84)] = 1021,
  [SMALL_STATE(85)] = 1028,
  [SMALL_STATE(86)] = 1035,
  [SMALL_STATE(87)] = 1042,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 4),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 5),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 6),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 8, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 8, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [225] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_crust(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "crust",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
